### ISSUE TITLE
Is it possible to render wiki links without the double bracket?

### ISSUE THREAD

**Issue by N0K0** [hikerpig/foam-template-gatsby-kb#13]
As per the current demo page:
![image](https://github.com/hikerpig/foam-template-gatsby-kb/assets/13900053/7f1eba38-9b9f-450d-8def-de6761b6ada0)

Is it possible to remove the brackets when rendering the web page? :)

**Comment by hikerpig** [comment]
This double bracket is kind of a builtin design for this theme.
Technically it's possible to make it configurable but it requires some changes in the code.

**Comment by N0K0** [comment]
Ah okay! No problem at all :D Thought it was a bug at first glance, but as a stylistic choice it makes sense! :+1:
