### ISSUE TITLE
Documents other than notes displaying on the table of contents?

### ISSUE THREAD

**Issue by GBrachetta** [hikerpig/foam-template-gatsby-kb#6]
Hi!

I wonder if there would be any way to display documents linked (like pdfs) on the left hand side table of contents and not just the md files.

![Knowledge_Base___My_Brain](https://user-images.githubusercontent.com/57924268/108732081-8331f700-752d-11eb-9737-fbdca7aa04e1.jpg)

I don't know if this is doable, but it would be great! 😄 

(mmm... I now realise mongodb-cheatsheet is not displaying there either... 🤔 . Need to check that)

**Comment by hikerpig** [comment]
The sidebar is not meant to be a file tree. For instance,  it displays the title rather than filename.
It's possible to shadow the component if you want to.
And yeah, it is also possible for developing a mechanism to let user provide custom  source for the sidebar, I just don't think that far yet.

**Comment by GBrachetta** [comment]
Ah, I didn't realise, thank you for clarifying!
