### ISSUE TITLE
How to add gatsby-remark-katex?

### ISSUE THREAD

**Issue by timothywangdev** [hikerpig/foam-template-gatsby-kb#7]
I'd like to render math equations with katex and I wonder where I should put the gatsby-remark-katex plugin? Thanks!

**Comment by hikerpig** [comment]
@timothywangdev At first I think it's pretty easy to add something to `defaultPluginMdx` just like other gatsby remark plugins in  `_layouts/gatsby-config.js`. But then I found there is an upstream problem of [gatsby-remark-katex Doesn’t work with gatsby-plugin-mdx](https://github.com/gatsbyjs/gatsby/issues/21866).

I tried some of the configs posted in the answers and no luck 😞.  Maybe we can track the issue and wait for the day that we can solve this simply by upgrading some dependencies.

**Comment by flashshare** [comment]
Any updates for gatsby-remark-katex? 
Maybe we can try with remark-math and rehype-katex

**Comment by hikerpig** [comment]
@flashshare I don't know if things have changed since last time I checked.  Maybe I will find sometime to look at it this week.

**Comment by flashshare** [comment]
@hikerpig 
These plugins work for me

    {
      resolve: "gatsby-plugin-mdx",
      options: {
        remarkPlugins: [require("remark-math")],
        rehypePlugins: [require("rehype-katex")],
      },
    },

**Comment by hikerpig** [comment]
@timothywangdev I've pushed a new commit to [support math notation](https://github.com/hikerpig/foam-template-gatsby-kb/commit/ea998f4e65dd783b59d8c0dff8c5b0551766bd7d).
The demo can be viewed in https://hikerpig.github.io/foam-template-gatsby-kb/math

**Comment by flashshare** [comment]
@hikerpig Great! This theme is indeed good. I hope it will be popular soon. Not only for foam users, but also for Obsidian users
